# Generated by Django 6.0.3 on 2026-03-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("courses", "0006_coursefile_quiz_url_alter_coursefile_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="公共消息关联的课程",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="courses.course",
                verbose_name="课程",
            ),
        ),
    ]
