# Generated by Django 5.0.1 on 2026-02-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="materials",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/materials/",
                verbose_name="课程资料",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="syllabus",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/syllabus/",
                verbose_name="课程大纲",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/attachments/",
                verbose_name="课时附件",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="attachment_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="附件名称"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/videos/",
                verbose_name="视频文件",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="courses/covers/", verbose_name="课程封面"
            ),
        ),
    ]
