# Generated by Django 5.0.1 on 2026-02-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_courserequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[("required", "必修"), ("elective", "选修")],
                max_length=20,
                verbose_name="课程类型",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "初级"),
                    ("intermediate", "中级"),
                    ("advanced", "高级"),
                ],
                max_length=20,
                null=True,
                verbose_name="难度级别",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="价格",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="副标题"
            ),
        ),
    ]
