# Generated by Django 5.0.1 on 2026-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_coursefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefile",
            name="quiz_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Quiz链接"
            ),
        ),
        migrations.AlterField(
            model_name="coursefile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/files/%Y/%m/",
                verbose_name="文件",
            ),
        ),
        migrations.AlterField(
            model_name="coursefile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("syllabus", "课程大纲"),
                    ("material", "课程资料"),
                    ("video", "视频资料"),
                    ("quiz", "Quiz"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=20,
                verbose_name="文件类型",
            ),
        ),
    ]
