# Generated by Django 6.0.2 on 2026-03-06 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0001_initial"),
        ("courses", "0005_coursefile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="测验标题")),
                (
                    "source_file",
                    models.FileField(
                        upload_to="quizzes/sources/%Y/%m/", verbose_name="源文件(PPT)"
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(max_length=255, verbose_name="源文件名"),
                ),
                (
                    "share_code",
                    models.CharField(
                        default="", max_length=32, unique=True, verbose_name="分享码"
                    ),
                ),
                (
                    "question_count",
                    models.IntegerField(default=5, verbose_name="题目数量"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否已发布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.course",
                        verbose_name="关联课程",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "测验",
                "verbose_name_plural": "测验",
                "db_table": "quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="题目内容")),
                ("option_a", models.CharField(max_length=500, verbose_name="选项A")),
                ("option_b", models.CharField(max_length=500, verbose_name="选项B")),
                ("option_c", models.CharField(max_length=500, verbose_name="选项C")),
                ("option_d", models.CharField(max_length=500, verbose_name="选项D")),
                (
                    "correct_answer",
                    models.CharField(max_length=1, verbose_name="正确答案"),
                ),
                ("explanation", models.TextField(blank=True, verbose_name="解析")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="ai_service.quiz",
                        verbose_name="测验",
                    ),
                ),
            ],
            options={
                "verbose_name": "测验题目",
                "verbose_name_plural": "测验题目",
                "db_table": "quiz_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField(default=dict, verbose_name="学生答案")),
                ("score", models.FloatField(default=0, verbose_name="得分")),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="总题数"),
                ),
                (
                    "correct_count",
                    models.IntegerField(default=0, verbose_name="正确数"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="ai_service.quiz",
                        verbose_name="测验",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "测验提交",
                "verbose_name_plural": "测验提交",
                "db_table": "quiz_submissions",
                "ordering": ["-submitted_at"],
                "unique_together": {("quiz", "student")},
            },
        ),
    ]
