# Generated by Django 5.0.1 on 2026-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0002_quiz_quizquestion_quizsubmission"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quizsubmission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="quiz",
            name="max_attempts",
            field=models.IntegerField(default=1, verbose_name="最大答题次数"),
        ),
    ]
