# Generated by Django 5.0.1 on 2026-04-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_coursefile_quiz_url_alter_coursefile_file_and_more"),
        ("ai_service", "0004_quiz_reminder_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="勋章代码")),
                ("title", models.CharField(max_length=100, verbose_name="勋章名称")),
                ("description", models.CharField(max_length=255, verbose_name="勋章说明")),
                ("icon", models.CharField(default="🏅", max_length=10, verbose_name="图标")),
                ("earned_at", models.DateTimeField(auto_now_add=True, verbose_name="获得时间")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debate_badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "辩论勋章",
                "verbose_name_plural": "辩论勋章",
                "db_table": "debate_badges",
                "ordering": ["-earned_at"],
                "unique_together": {("student", "code")},
            },
        ),
        migrations.CreateModel(
            name="DebateMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200, verbose_name="辩题")),
                ("ai_claim", models.TextField(verbose_name="AI观点")),
                (
                    "status",
                    models.CharField(
                        choices=[("ongoing", "进行中"), ("won", "获胜"), ("lost", "失败")],
                        default="ongoing",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("rounds_count", models.IntegerField(default=0, verbose_name="回合数")),
                ("total_attack", models.IntegerField(default=0, verbose_name="累计攻击力")),
                ("best_attack", models.IntegerField(default=0, verbose_name="最高攻击力")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debate_matches",
                        to="courses.course",
                        verbose_name="关联课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debate_matches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "辩论对战",
                "verbose_name_plural": "辩论对战",
                "db_table": "debate_matches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DebateRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField(verbose_name="回合序号")),
                ("student_argument", models.TextField(verbose_name="学生反驳")),
                ("ai_counter", models.TextField(verbose_name="AI反击")),
                ("logic_score", models.IntegerField(default=0, verbose_name="逻辑得分")),
                ("evidence_score", models.IntegerField(default=0, verbose_name="证据得分")),
                ("knowledge_score", models.IntegerField(default=0, verbose_name="知识得分")),
                ("structure_score", models.IntegerField(default=0, verbose_name="结构得分")),
                ("attack_power", models.IntegerField(default=0, verbose_name="攻击力")),
                ("verdict", models.CharField(blank=True, max_length=100, verbose_name="本回合评价")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="ai_service.debatematch",
                        verbose_name="对战",
                    ),
                ),
            ],
            options={
                "verbose_name": "辩论回合",
                "verbose_name_plural": "辩论回合",
                "db_table": "debate_rounds",
                "ordering": ["created_at"],
                "unique_together": {("match", "round_number")},
            },
        ),
    ]
